### PR TITLE
Change & get audio level of lock

### PR DESCRIPTION
**Pull request by albinmedoc**
I have added function to get and set audio level of the door lock.
The accepted values are SILENCE, LOW & HIGH.

Whats left to do is to add an accessory reflecting this.

### CODE REVIEW

**Comment by albinmedoc** [comment]
I don't know if we could use [this](https://developers.homebridge.io/#/service/InputSource)?

**Comment by ptz0n** [comment]
I believe this one should be a good fit: https://developers.homebridge.io/#/service/Speaker

**Comment by albinmedoc** [comment]
Looks good. I will give it a try.

**Comment by albinmedoc** [comment]
I have now implemented and tested the mute/unmute functionality. 

I'm not sure how to implement the volume. One idea I have is the following:

If volume set to 0 = set to SILENCE
If volume set to <= 50 = set to LOW
If volume set to > 50 = set to HIGH

**Comment by albinmedoc** [comment]
Otherwise we could leave it as it is now. 
Mute = SILENCE
Unmute = HIGH

**Comment by ptz0n** [comment]
I don't have this accessory in my installation so I guess you as an end user get to decide what makes the most sense.

**Comment by albinmedoc** [comment]
I have now created a switch that toggles the audio level. The speaker accessory was only visible in the Eve-app. 

By using a switch we can only use two of the three volume settings...
I updated the configuration so the user can specify what volume setting will be applied on switch on/off.  

I also added an option to hide this switch, and while I was at I did the same for the Auto Lock switch ([#94](https://github.com/ptz0n/homebridge-verisure/issues/94)).

**Comment by albinmedoc** [comment]
If this PR gets accepted we can close [#94](https://github.com/ptz0n/homebridge-verisure/issues/94) & [#144](https://github.com/ptz0n/homebridge-verisure/issues/144).

**Comment by ptz0n** [comment]
I've done some cleanup and added tests. Please let me push to https://github.com/albinmedoc/homebridge-verisure.

**Pull request merged**
